version: "3"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:6-alpine
    volumes:
      - redis-data:/data

volumes:
  redis-data:
